# Generated by Django 6.0.6 on 2026-08-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_outdated',
            field=models.BooleanField(default=False),
        ),
    ]
