# Generated by Django 6.0.6 on 2026-08-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_is_outdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='provider',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
